-- Versioned schema migration: payroll_records
CREATE TABLE IF NOT EXISTS `payroll_records` (
  `id` bigint UNSIGNED NOT NULL,
  `employee_id` bigint UNSIGNED NOT NULL,
  `payroll_period` char(7) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_date` date NOT NULL,
  `employee_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_nik` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_position` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `base_salary` decimal(18,2) NOT NULL DEFAULT '0.00',
  `health_company_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `health_employee_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `jht_company_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `jht_employee_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `jp_company_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `jp_employee_rate` decimal(8,4) NOT NULL DEFAULT '0.0000',
  `health_company_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `health_employee_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `jht_company_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `jht_employee_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `jp_company_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `jp_employee_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `employee_bpjs_deduction` decimal(18,2) NOT NULL DEFAULT '0.00',
  `employer_bpjs_contribution` decimal(18,2) NOT NULL DEFAULT '0.00',
  `net_pay` decimal(18,2) NOT NULL DEFAULT '0.00',
  `salary_expense_account_id` bigint UNSIGNED NOT NULL,
  `bpjs_expense_account_id` bigint UNSIGNED NOT NULL,
  `cash_account_id` bigint UNSIGNED NOT NULL,
  `bpjs_payable_account_id` bigint UNSIGNED NOT NULL,
  `journal_entry_id` bigint UNSIGNED DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `status` enum('draft','posted','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `overtime_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `allowance_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `bonus_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `loan_deduction` decimal(15,2) NOT NULL DEFAULT '0.00',
  `other_deduction` decimal(15,2) NOT NULL DEFAULT '0.00',
  `pph21_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `tax_record_id` bigint UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
